### ISSUE TITLE
The speed to extract the flow map is too slow

### ISSUE THREAD

**Issue by GuardSkill** [craston/MARS#15]
The speed to extract the flow map is too slow > _ <

**Comment by GuardSkill** [comment]
I sincerely appreciate the provided code, and will heartfelt thank you if you would like to provide the extracted optical flow dataset for UCF or HMDB51-1.

**Comment by craston** [comment]
Hi,

I understand that extracting optical flows using TV-L1 (with GPU support) takes time. You could use another methods to estimate optical flow like PWC-Net which is faster to compute but less accurate than TV-L1. However, RGB+PWCNet Flow gives comparable performance to RGB+TVL1Flow.

Since I  switched jobs recently, I no longer have access to the extracted flows for UCF101 and HMDB51. Sorry.

**Comment by GuardSkill** [comment]
Okay,  thanks for your great contribution!!!. I will try to write a multiprocess program to improve speed.

**Comment by tadbeer** [comment]
outputs_Flow = model_Flow(inputs_Flow)[1].detach()
IndexError: list index out of range

Getting this error. What is the mistake i am doing ?

**Comment by craston** [comment]
@tadbeer could you please check the shape for model_Flow(inputs_Flow). Also could you provide the script with argument values
